'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace CustomersService
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CustomerOrdersSoap", [Namespace]:="http://www.wrox.com/webservices/4923/customer-orders")>  _
    Public Class CustomerOrders
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/4923/customer-orders/webservices/customer-data.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wrox.com/webservices/4923/customer-orders/GetCustomers", RequestNamespace:="http://www.wrox.com/webservices/4923/customer-orders", ResponseNamespace:="http://www.wrox.com/webservices/4923/customer-orders", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCustomers(ByVal strCustID As String, ByVal strCustName As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetCustomers", New Object() {strCustID, strCustName})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetCustomers(ByVal strCustID As String, ByVal strCustName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetCustomers", New Object() {strCustID, strCustName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetCustomers(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wrox.com/webservices/4923/customer-orders/GetOrders", RequestNamespace:="http://www.wrox.com/webservices/4923/customer-orders", ResponseNamespace:="http://www.wrox.com/webservices/4923/customer-orders", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetOrders(ByVal strCustID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetOrders", New Object() {strCustID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetOrders(ByVal strCustID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetOrders", New Object() {strCustID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetOrders(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
