//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
// 
namespace Local.Customers {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerOrdersSoap", Namespace="http://www.wrox.com/webservices/4923/customer-orders")]
    public class CustomerOrders : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CustomerOrders() {
            this.Url = "http://localhost/4923/customer-orders/webservices/customer-data.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wrox.com/webservices/4923/customer-orders/GetCustomers", RequestNamespace="http://www.wrox.com/webservices/4923/customer-orders", ResponseNamespace="http://www.wrox.com/webservices/4923/customer-orders", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCustomers(string strCustID, string strCustName) {
            object[] results = this.Invoke("GetCustomers", new object[] {
                        strCustID,
                        strCustName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomers(string strCustID, string strCustName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomers", new object[] {
                        strCustID,
                        strCustName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetCustomers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.wrox.com/webservices/4923/customer-orders/GetOrders", RequestNamespace="http://www.wrox.com/webservices/4923/customer-orders", ResponseNamespace="http://www.wrox.com/webservices/4923/customer-orders", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrders(string strCustID) {
            object[] results = this.Invoke("GetOrders", new object[] {
                        strCustID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrders(string strCustID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrders", new object[] {
                        strCustID}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetOrders(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
